/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Header: (typeof import('./components/main-header/Header.vue'))['default']
    HeaderSearch: (typeof import('./views/main/system/account/cpns/header-search.vue'))['default']
    MainHeader: (typeof import('./components/main-header/mainHeader.vue'))['default']
    MainMenu: (typeof import('./components/main-menu/main-menu.vue'))['default']
    RouterLink: (typeof import('vue-router'))['RouterLink']
    RouterView: (typeof import('vue-router'))['RouterView']
    TableContent: (typeof import('./views/main/system/account/cpns/table-content.vue'))['default']
  }
}
